version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: symtalk
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+09:00
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symtalk_net

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - symtalk_net

  application:
    container_name: symtalk-be
    image: ccjngwn/symtalk-be:latest
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env.prod
    depends_on:
      - mysql
      - redis
    networks:
      - symtalk_net

  nginx:
    container_name: nginx
    image: ccjngwn/nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/compose/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - application
    networks:
      - symtalk_net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mysql_data:
  redis_data:

networks:
  symtalk_net: {}
