version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: symtalk
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symtalk_net

  application:
    container_name: symtalk-be
    image: ccjngwn/symtalk-be:latest
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - symtalk_net

  nginx:
    container_name: nginx
    image: ccjngwn/nginx:latest
    ports:
      - 80:80
      # 도메인 발급 후 HTTPS 포트 활성화
      # - 443:443
    # 도메인 발급 후 SSL 인증서 볼륨 활성화
    # volumes:
    #   - ./certbot/conf:/etc/letsencrypt
    #   - ./certbot/www:/var/www/certbot
    depends_on:
      - application
    networks:
      - symtalk_net
    # 도메인 발급 후 certbot 자동 갱신 활성화
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # 도메인 발급 후 certbot 활성화
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mysql_data:

networks:
  symtalk_net: {}
