spring:
  application:
    name: itda-backend

  # .env ??? Spring ???? ???? ?? ??
  # - ???? ??? .env(.properties) ??? ?? ?? ???? ????.
  # - DB ????, Redis ???? ? ?? ??? .env?? ????.
  config:
    import: optional:file:.env[.properties]

  jackson:
    time-zone: Asia/Seoul        # KST ???? ???
    serialization:
      write-dates-as-timestamps: false  # 2025-11-28T13:00:00 ?? ISO ???? ??

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

# ?? ?? ?? ??
# TRACE -> DEBUG -> INFO -> WARN -> ERROR -> OFF ?
# root? ?? ?? ??? ????, com.cotato.itda ???? ?? ??? DEBUG? ??
logging:
  level:
    root: INFO
    com.cotato.itda: DEBUG